parameters:
- name: platformPrefix
  type: string
- name: excludePrefixes
  type: object
  default: []

jobs:
- job: CheckCommitMessage
  displayName: 'Check Commit Message'
  steps:
  - script: |
      COMMIT_MSG="$(Build.SourceVersionMessage)"
      echo "Commit message: $COMMIT_MSG"
      
      # Check if this platform should run
      if [[ "$COMMIT_MSG" == *"${{ parameters.platformPrefix }}"* ]] || [[ $(echo "${{ join(',', parameters.excludePrefixes) }}" | grep -v -E "$(echo "$COMMIT_MSG" | grep -oE '\[[a-z]+\]' || echo 'none')") ]]; then
        echo "✓ Pipeline should run for this platform"
        echo "##vso[task.setvariable variable=ShouldRun;isOutput=true]true"
        
        # Set conditional variables
        if [[ "$COMMIT_MSG" == *"[release]"* ]] && [[ "$(Build.SourceBranch)" != "refs/heads/main" ]] && [[ "$(Build.SourceBranch)" != "refs/heads/master" ]]; then
          echo "##vso[task.setvariable variable=ShouldCreatePR;isOutput=true]true"
          echo "##vso[task.setvariable variable=ShouldRelease;isOutput=true]false"
        elif [[ "$(Build.SourceBranch)" == "refs/heads/main" ]] || [[ "$(Build.SourceBranch)" == "refs/heads/master" ]]; then
          echo "##vso[task.setvariable variable=ShouldCreatePR;isOutput=true]false"
          echo "##vso[task.setvariable variable=ShouldRelease;isOutput=true]true"
        else
          echo "##vso[task.setvariable variable=ShouldCreatePR;isOutput=true]false"
          echo "##vso[task.setvariable variable=ShouldRelease;isOutput=true]false"
        fi
      else
        echo "✗ Pipeline should not run for this platform"
        echo "##vso[task.setvariable variable=ShouldRun;isOutput=true]false"
        exit 1
      fi
    displayName: 'Parse commit message and set variables'
    name: commitCheck