jobs:
- job: CreatePullRequest
  displayName: 'Create Pull Request to Main'
  steps:
  - script: |
      echo "Installing GitHub CLI..."
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      sudo apt update
      sudo apt install gh -y
      
      echo "Creating pull request..."
      
      # Configure git
      git config --global user.email "pipeline@company.com"
      git config --global user.name "Azure DevOps"
      
      # Get current branch name
      CURRENT_BRANCH="$(Build.SourceBranchName)"
      echo "Current branch: $CURRENT_BRANCH"
      
      # Determine target branch
      git fetch origin
      if git ls-remote --heads origin main | grep -q main; then
        TARGET_BRANCH="main"
      else
        TARGET_BRANCH="master"
      fi
      echo "Target branch: $TARGET_BRANCH"
      
      # Authenticate with GitHub
      echo "$GITHUB_TOKEN" | gh auth login --with-token
      
      # Create PR
      COMMIT_MSG="$(Build.SourceVersionMessage)"
      PR_TITLE="Release: $(echo "$COMMIT_MSG" | head -n1 | sed 's/\[.*\]//g' | xargs)"
      
      gh pr create \
        --title "$PR_TITLE" \
        --body "Automated PR created by Azure DevOps

      Commit: $COMMIT_MSG

      Ready for review and release approval." \
        --head "$CURRENT_BRANCH" \
        --base "$TARGET_BRANCH"
      
      echo "✓ Pull request created successfully"
    displayName: 'Create Pull Request'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)