parameters:
- name: ciTool
  type: string
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: workspacePrefix
  type: string
- name: terraformCloudToken
  type: string
- name: azureCredentials
  type: object

stages:
- stage: Plan
  displayName: 'Plan Infrastructure'
  jobs:
  - job: CommitCheck
    displayName: 'Check Commit Message'
    steps:
    - script: |
        COMMIT_MSG="$(Build.SourceVersionMessage)"
        if [[ "$COMMIT_MSG" == *"[${{ parameters.ciTool }}]"* ]]; then
          echo "##vso[task.setvariable variable=shouldRun;isOutput=true]true"
        else
          echo "##vso[task.setvariable variable=shouldRun;isOutput=true]false"
          echo "Skipping - commit message doesn't contain [${{ parameters.ciTool }}]"
        fi
        
        if [[ "$COMMIT_MSG" == *"[apply]"* ]]; then
          echo "##vso[task.setvariable variable=shouldApply;isOutput=true]true"
        else
          echo "##vso[task.setvariable variable=shouldApply;isOutput=true]false"
        fi
      name: commitCheck
      displayName: 'Parse Commit Message'

  - job: PlanDev
    displayName: 'Plan Dev Environment'
    dependsOn: CommitCheck
    condition: eq(dependencies.CommitCheck.outputs['commitCheck.shouldRun'], 'true')
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '${{ parameters.terraformVersion }}'
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: 'Install Azure CLI'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "${{ parameters.terraformCloudToken }}"
        }
        EOF
        terraform init -reconfigure
        terraform plan -detailed-exitcode
        PLAN_EXIT_CODE=$?
        if [ $PLAN_EXIT_CODE -eq 0 ]; then
          echo "✅ No changes detected"
        elif [ $PLAN_EXIT_CODE -eq 2 ]; then
          echo "✅ Changes detected - plan successful"
        else
          echo "❌ Plan failed"
          exit $PLAN_EXIT_CODE
        fi
      displayName: 'Plan Dev'
      env:
        TF_WORKSPACE: ${{ parameters.workspacePrefix }}-dev
        ARM_CLIENT_ID: ${{ parameters.azureCredentials.clientId }}
        ARM_CLIENT_SECRET: ${{ parameters.azureCredentials.clientSecret }}
        ARM_SUBSCRIPTION_ID: ${{ parameters.azureCredentials.subscriptionId }}
        ARM_TENANT_ID: ${{ parameters.azureCredentials.tenantId }}

- stage: Dev
  displayName: 'Deploy to Development'
  dependsOn: Plan
  condition: and(succeeded(), eq(stageDependencies.Plan.CommitCheck.outputs['commitCheck.shouldApply'], 'true'))
  jobs:
  - job: DeployDev
    displayName: 'Apply Dev Environment'
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '${{ parameters.terraformVersion }}'
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: 'Install Azure CLI'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "${{ parameters.terraformCloudToken }}"
        }
        EOF
        terraform init
        terraform apply -auto-approve
      displayName: 'Apply Dev'
      env:
        TF_WORKSPACE: ${{ parameters.workspacePrefix }}-dev
        ARM_CLIENT_ID: ${{ parameters.azureCredentials.clientId }}
        ARM_CLIENT_SECRET: ${{ parameters.azureCredentials.clientSecret }}
        ARM_SUBSCRIPTION_ID: ${{ parameters.azureCredentials.subscriptionId }}
        ARM_TENANT_ID: ${{ parameters.azureCredentials.tenantId }}

- stage: Staging
  displayName: 'Deploy to Staging'
  dependsOn: Dev
  condition: false
  jobs:
  - job: DeployStaging
    displayName: 'Apply Staging Environment'
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '${{ parameters.terraformVersion }}'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "${{ parameters.terraformCloudToken }}"
        }
        EOF
        terraform init
        terraform apply -auto-approve
      displayName: 'Apply Staging'
      env:
        TF_WORKSPACE: ${{ parameters.workspacePrefix }}-staging
        ARM_CLIENT_ID: ${{ parameters.azureCredentials.clientId }}
        ARM_CLIENT_SECRET: ${{ parameters.azureCredentials.clientSecret }}
        ARM_SUBSCRIPTION_ID: ${{ parameters.azureCredentials.subscriptionId }}
        ARM_TENANT_ID: ${{ parameters.azureCredentials.tenantId }}

- stage: Prod
  displayName: 'Deploy to Production'
  dependsOn: Staging
  condition: false
  jobs:
  - deployment: DeployProd
    displayName: 'Apply Production Environment'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '${{ parameters.terraformVersion }}'
          - script: |
              export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
              cat > $(Agent.TempDirectory)/.terraformrc << EOF
              credentials "app.terraform.io" {
                token = "${{ parameters.terraformCloudToken }}"
              }
              EOF
              terraform init
              terraform apply -auto-approve
            displayName: 'Apply Production'
            env:
              TF_WORKSPACE: ${{ parameters.workspacePrefix }}-prod
              ARM_CLIENT_ID: ${{ parameters.azureCredentials.clientId }}
              ARM_CLIENT_SECRET: ${{ parameters.azureCredentials.clientSecret }}
              ARM_SUBSCRIPTION_ID: ${{ parameters.azureCredentials.subscriptionId }}
              ARM_TENANT_ID: ${{ parameters.azureCredentials.tenantId }}